# Generated by Django 2.2.1 on 2019-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ManyToManyField(related_name='repositories', to='github.User'),
        ),
    ]
