# Generated by Django 2.2.1 on 2019-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20190508_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
