# Generated by Django 2.2.1 on 2019-05-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20190508_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='github.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
