# Generated by Django 2.2.1 on 2019-05-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_auto_20190508_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
