# Generated by Django 2.2.1 on 2019-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0009_auto_20190509_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='forks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
